version: "3.8"
services:
    nodeserver:
        build:
          context: ./node
          dockerfile: Dockerfile.prod
        container_name: nodeserver
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
        restart: always
        volumes:
          - ./node:/usr/src/app
        tty: true
        ports:
          - "5000:5000"
        depends_on:
          - db
        networks:
          - nodenet

    nginx:
        container_name: nginx
        # entrypoint: dockerize -wait tcp://db:5000 -timeout 20s docker-entrypoint.sh
        restart: always
        build:
          context: ./nginx
        ports:
          - "8080:80"
        depends_on:
          - nodeserver
        networks:
          - nodenet

    db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      # caso o docker caia, os dados estao salvos por compatilhamento de volumes 
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=root
      networks:
          - nodenet
        

networks:
  nodenet:
    driver: bridge